<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vanara.PInvoke.Security" />
    <PackageReference Include="Vanara.PInvoke.NetApi32" />
    <PackageReference Include="Vanara.PInvoke.User32" />
  </ItemGroup>

</Project>
