<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
    <VanaraVer>5.0.5</VanaraVer>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AvalonEdit" Version="6.3.1.120" />
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
    <PackageVersion Include="ConEmu.Control.WinForms" Version="1.21.9.5" />
    <PackageVersion Include="DirectShowLib.Standard" Version="2.1.0" />
    <PackageVersion Include="Markdig" Version="1.1.2" />
    <PackageVersion Include="Microsoft.Direct3D.D3D12" Version="1.619.1" />
    <PackageVersion Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageVersion Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageVersion Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7705" />
    <PackageVersion Include="Microsoft.Windows.SDK.Contracts" Version="10.0.26100.7705" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.8.260209005" />
    <PackageVersion Include="NuGet.Commands" Version="7.3.0" />
    <PackageVersion Include="NuGet.Versioning" Version="7.3.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageVersion Include="System.Data.OleDb" Version="10.0.4" />
    <PackageVersion Include="System.Drawing.Common" Version="10.0.4" />
    <PackageVersion Include="System.Management" Version="10.0.4" />
    <PackageVersion Include="Vanara.BITS" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.CodeGen" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.Core" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.DirectoryServices" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.Library" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.AclUI" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.ActiveDS" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.AMSI" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Avrt" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.BITS" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.CimFs" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.CldApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.ComCtl32" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.ComDlg32" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.CoreAudio" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.CredUI" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Cryptography" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.D3DCompiler" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Dcomp" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Dhcp" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Direct2D" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Direct3D11" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Direct3D12" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.DirectX" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.DnsApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Drt" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.DwmApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.ElsCore" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.EnhancedStorage" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.FhSvcCtl" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.FirewallApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.FunDisc" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Gdi32" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.HttpApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.IMAPI" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.IpHlpApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.IScsiDsc" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Kernel32" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Magnification" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Mpr" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.MsftEdit" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Multimedia" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.NetApi32" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.NetListMgr" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.NTDSApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Odbc32" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Ole" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.OleDB" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Opc" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.P2P" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Pdh" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.PortableDeviceApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.PowrProf" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Printing" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.ProjectedFSLib" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.QoS" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Rpc" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.RstrtMgr" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.SearchApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Security" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.SensorsApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.SetupAPI" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.SHCore" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Shell32" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Shlwapi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.SpeechApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.SpellCheckingApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.TelephonyApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.TextServicesFramework" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.UIAnimation" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.UrlMon" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.User32" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.UxTheme" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.VssApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.WcmApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.WcnApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.WebSocket" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.WinHTTP" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.WinINet" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.WinTrust" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.WlanApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.Ws2_32" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.PInvoke.WscApi" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.VirtualDisk" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.Windows.Extensions" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.Windows.Forms" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.Windows.Shell" Version="$(VanaraVer)" />
    <PackageVersion Include="Vanara.Windows.Shell.Common" Version="$(VanaraVer)" />
  </ItemGroup>
</Project>