//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace explorerdataprovider.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("explorerdataprovider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        internal static string IDS_0 {
            get {
                return ResourceManager.GetString("IDS_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        internal static string IDS_1 {
            get {
                return ResourceManager.GetString("IDS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        internal static string IDS_2 {
            get {
                return ResourceManager.GetString("IDS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        internal static string IDS_3 {
            get {
                return ResourceManager.GetString("IDS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        internal static string IDS_4 {
            get {
                return ResourceManager.GetString("IDS_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five.
        /// </summary>
        internal static string IDS_5 {
            get {
                return ResourceManager.GetString("IDS_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five or Greater.
        /// </summary>
        internal static string IDS_5ORGREATER {
            get {
                return ResourceManager.GetString("IDS_5ORGREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six.
        /// </summary>
        internal static string IDS_6 {
            get {
                return ResourceManager.GetString("IDS_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven.
        /// </summary>
        internal static string IDS_7 {
            get {
                return ResourceManager.GetString("IDS_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight.
        /// </summary>
        internal static string IDS_8 {
            get {
                return ResourceManager.GetString("IDS_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine.
        /// </summary>
        internal static string IDS_9 {
            get {
                return ResourceManager.GetString("IDS_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string IDS_CIRCLE {
            get {
                return ResourceManager.GetString("IDS_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string IDS_DISPLAY {
            get {
                return ResourceManager.GetString("IDS_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the item..
        /// </summary>
        internal static string IDS_DISPLAY_TT {
            get {
                return ResourceManager.GetString("IDS_DISPLAY_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string IDS_EXPLORE {
            get {
                return ResourceManager.GetString("IDS_EXPLORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Item.
        /// </summary>
        internal static string IDS_EXPLORE_HELP {
            get {
                return ResourceManager.GetString("IDS_EXPLORE_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        internal static string IDS_GROUPBYALPHA {
            get {
                return ResourceManager.GetString("IDS_GROUPBYALPHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by Level.
        /// </summary>
        internal static string IDS_GROUPBYLEVEL {
            get {
                return ResourceManager.GetString("IDS_GROUPBYLEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Sides.
        /// </summary>
        internal static string IDS_GROUPBYSIDES {
            get {
                return ResourceManager.GetString("IDS_GROUPBYSIDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by Size.
        /// </summary>
        internal static string IDS_GROUPBYSIZE {
            get {
                return ResourceManager.GetString("IDS_GROUPBYSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by Value.
        /// </summary>
        internal static string IDS_GROUPBYVALUE {
            get {
                return ResourceManager.GetString("IDS_GROUPBYVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string IDS_LARGE {
            get {
                return ResourceManager.GetString("IDS_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than 5.
        /// </summary>
        internal static string IDS_LESSTHAN5 {
            get {
                return ResourceManager.GetString("IDS_LESSTHAN5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string IDS_MEDIUM {
            get {
                return ResourceManager.GetString("IDS_MEDIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string IDS_OPEN {
            get {
                return ResourceManager.GetString("IDS_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Item in New Window.
        /// </summary>
        internal static string IDS_OPEN_HELP {
            get {
                return ResourceManager.GetString("IDS_OPEN_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        internal static string IDS_POLYGON {
            get {
                return ResourceManager.GetString("IDS_POLYGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        internal static string IDS_RECTANGLE {
            get {
                return ResourceManager.GetString("IDS_RECTANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting 1.
        /// </summary>
        internal static string IDS_SETTING1 {
            get {
                return ResourceManager.GetString("IDS_SETTING1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify setting 1..
        /// </summary>
        internal static string IDS_SETTING1_TT {
            get {
                return ResourceManager.GetString("IDS_SETTING1_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting 2.
        /// </summary>
        internal static string IDS_SETTING2 {
            get {
                return ResourceManager.GetString("IDS_SETTING2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify setting 2..
        /// </summary>
        internal static string IDS_SETTING2_TT {
            get {
                return ResourceManager.GetString("IDS_SETTING2_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting 3.
        /// </summary>
        internal static string IDS_SETTING3 {
            get {
                return ResourceManager.GetString("IDS_SETTING3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify setting 3..
        /// </summary>
        internal static string IDS_SETTING3_TT {
            get {
                return ResourceManager.GetString("IDS_SETTING3_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string IDS_SETTINGS {
            get {
                return ResourceManager.GetString("IDS_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify settings..
        /// </summary>
        internal static string IDS_SETTINGS_TT {
            get {
                return ResourceManager.GetString("IDS_SETTINGS_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string IDS_SMALL {
            get {
                return ResourceManager.GetString("IDS_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Data Provider.
        /// </summary>
        internal static string IDS_TITLE {
            get {
                return ResourceManager.GetString("IDS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        internal static string IDS_TRIANGLE {
            get {
                return ResourceManager.GetString("IDS_TRIANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        internal static string IDS_UNSPECIFIED {
            get {
                return ResourceManager.GetString("IDS_UNSPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string IDS_VALUE {
            get {
                return ResourceManager.GetString("IDS_VALUE", resourceCulture);
            }
        }
    }
}
